[node]
detect-drivers= false

[[node.driver-configuration]]
max-sessions= 5
display-name= "chrome"
stereotype= "{\"browserName\":\"chrome\"}"

[[node.driver-configuration]]
max-sessions= 5
display-name= "firefox"
stereotype= "{\"browserName\":\"firefox\"}"