[node]
detect-drivers= false


[sessionqueue]
session-request-timeout = 10000

[[node.driver-configuration]]
max-sessions= 5
display-name= "chrome"
stereotype= "{\"browserName\":\"chrome\"}"


[[node.driver-configuration]]
max-sessions= 5
display-name= "firefox"
stereotype= "{\"browserName\":\"firefox\"}"


[[node.driver-configuration]]
max-sessions= 5
display-name= "edge"
stereotype= "{\"browserName\":\"MicrosoftEdge\"}"